### PR TITLE
adds Mojo support

### PR DESCRIPTION
**Pull request by collinjackson**

### CODE REVIEW

**Comment by sethladd** [comment]
cc @kevmoo @davenotik

Could we ask one of you to give us a review? We're making this package work both for JS and Mojo. Thanks very much for your review!

**Comment by kevmoo** [comment]
If you create a pull request, travis will kick in – which is nice

**Comment by collinjackson** [comment]
Moved discussion to https://github.com/firebase/firebase-dart/pull/70

**Comment by kevmoo** [comment]
What's the story here? Just curious...

**Comment by collinjackson** [comment]
Flutter's firebase plugin got moved into to [flutter/plugins](https://github.com/flutter/plugins) and is no longer a fork of [firebase/firebase-dart](https://github.com/firebase/firebase-dart). Since Flutter no longer provides mojo support, this pull request is obsolete.

**Comment by kevmoo** [comment]
I figured 😊

From mobile. Sorry for brevity and/or spelling.

On Aug 29, 2017 13:01, "Collin Jackson" <notifications@github.com> wrote:

Flutter's firebase plugin got moved into to flutter/plugins and is no
longer a fork of firebase/firebase-dart. Since Flutter no longer provides
mojo support, this pull request is obsolete.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/collinjackson/firebase-dart/pull/1#issuecomment-325782872>,
or mute the thread

**Pull request closed without merging**
